stages:
  - build
  - push
  - test
  - deploy

variables:
  REGISTRY: "registry.gitlab.com"
  IMAGE_NAME: "$REGISTRY/Hsu-28/autoratecicd"
  DOCKER_DRIVER: overlay2

# Build stage
build_backend:
  stage: build
  script:
    - docker build -t $IMAGE_NAME/backend:latest ./back-end
  tags:
    - docker
  only:
    - master

build_frontend:
  stage: build
  script:
    - docker build -t $IMAGE_NAME/frontend:latest ./front-end
  tags:
    - docker
  only:
    - master

build_rateapi:
  stage: build
  script:
    - docker build -t $IMAGE_NAME/rateapi:latest ./rate-api
  tags:
    - docker
  only:
    - master

# Push stage
push_backend:
  stage: push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY
    - docker push $IMAGE_NAME/backend:latest
  tags:
    - docker
  only:
    - master

push_frontend:
  stage: push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY
    - docker push $IMAGE_NAME/frontend:latest
  tags:
    - docker
  only:
    - master

push_rateapi:
  stage: push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY
    - docker push $IMAGE_NAME/rateapi:latest
  tags:
    - docker
  only:
    - master

# Test stage
test_services:
  stage: test
  script:
    - docker run -d --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=MyP@ssw0rd123! -p 1433:1433 --network mynetwork mcr.microsoft.com/mssql/server:2019-latest
    - docker-compose -f docker-compose.yml up -d
    - sleep 30
    - docker-compose -f docker-compose.yml down
  tags:
    - docker
  only:
    - master

# Deploy stage
deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
  tags:
    - docker
  only:
    - master
