image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - push
  - test
  - deploy

variables:
  REGISTRY: "registry.gitlab.com"
  IMAGE_NAME: "$REGISTRY/hsu-28/autoratecicd"

# Build stage
build_backend:
  stage: build
  script:
    - docker build -t $IMAGE_NAME/backend:latest ./back-end
  only:
    - master

build_frontend:
  stage: build
  script:
    - docker build -t $IMAGE_NAME/frontend:latest ./front-end
  only:
    - master

build_rateapi:
  stage: build
  script:
    - docker build -t $IMAGE_NAME/rateapi:latest ./rate-api
  only:
    - master

# Push stage
push_backend:
  stage: push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY
    - docker push $IMAGE_NAME/backend:latest
  only:
    - master

push_frontend:
  stage: push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY
    - docker push $IMAGE_NAME/frontend:latest
  only:
    - master

push_rateapi:
  stage: push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY
    - docker push $IMAGE_NAME/rateapi:latest
  only:
    - master

# Test stage
test_services:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up -d
    - sleep 30  # 等待服务启动
    - docker-compose -f docker-compose.yml down
  only:
    - master

# Deploy stage
deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - master
