stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

build_backend:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build backend
  tags:
    - docker

build_frontend:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build frontend
  tags:
    - docker

build_rateapi:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build rateapi
  tags:
    - docker

test_containers:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up -d
    - docker ps -a  # 列出所有容器以確認它們是否已啟動
    - docker-compose -f docker-compose.yml exec backend curl -f http://localhost:5000 || exit 1
    - docker-compose -f docker-compose.yml exec frontend curl -f http://localhost || exit 1
    - docker-compose -f docker-compose.yml exec rateapi curl -f http://localhost:6000 || exit 1
  tags:
    - docker
  after_script:
    - docker-compose -f docker-compose.yml down
