stages:
  - build
  - test
  - deploy

# 构建阶段
build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    # 构建所有服务的 Docker 镜像
    - docker-compose build
    # 推送每个服务的 Docker 镜像到 GitLab 容器注册表
    - docker tag my-backend:latest registry.gitlab.com/Hsu-28/Autoratecicd/backend:latest
    - docker push registry.gitlab.com/Hsu-28/Autoratecicd/backend:latest
    - docker tag my-frontend:latest registry.gitlab.com/Hsu-28/Autoratecicd/frontend:latest
    - docker push registry.gitlab.com/Hsu-28/Autoratecicd/frontend:latest
    - docker tag my-rateapi:latest registry.gitlab.com/Hsu-28/Autoratecicd/rateapi:latest
    - docker push registry.gitlab.com/Hsu-28/Autoratecicd/rateapi:latest

# 测试阶段
test:
  stage: test
  image: python:3.8
  script:
    # 运行测试，通常在你的测试容器中
    - docker run --rm -v $(pwd):/app -w /app my-backend:latest pytest

# 部署阶段
deploy:
  stage: deploy
  image: kubectl:1.21.0
  script:
    # 应用 Kubernetes 部署文件
    - kubectl apply -f k8s/deployment.yaml
  environment:
    name: production
  when: manual
