stages:
  - build
  - push
  - test
  - deploy

variables:
  REGISTRY: "registry.gitlab.com"
  IMAGE_NAME: "$REGISTRY/hsu-28/autoratecicd"

# Build and push backend
build_and_push_backend:
  stage: build
  script:
    - docker build -t $IMAGE_NAME/backend:latest ./back-end
    - docker push $IMAGE_NAME/backend:latest
  only:
    - master

# Build and push frontend
build_and_push_frontend:
  stage: build
  script:
    - docker build -t $IMAGE_NAME/frontend:latest ./front-end
    - docker push $IMAGE_NAME/frontend:latest
  only:
    - master

# Build and push rateapi
build_and_push_rateapi:
  stage: build
  script:
    - docker build -t $IMAGE_NAME/rateapi:latest ./rate-api
    - docker push $IMAGE_NAME/rateapi:latest
  only:
    - master

# Test stage
test_services:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up -d
    - sleep 30  # 等待服務啟動
    - docker-compose -f docker-compose.yml down
  only:
    - master

# Deploy stage
deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - master
