[[runners]]
  name = "my-runner"
  url = "https://gitlab.com/"  # 设置为 GitLab 实例的根地址
  token = "GR134894145GvXAF71xFy7-7Fy3DR"  # 用你的 Runner Token 替换
  executor = "docker"  # 根据需要选择合适的执行器
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"  # 默认的 Docker 镜像
    privileged = true       # 允许特权模式
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_legacy_registries = false
    volumes = ["/cache"]
    shm_size = 0

  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

  [runners.custom_build_dir]